### ISSUE TITLE
Wrong exit code for `system()` for success

### ISSUE THREAD

**Issue by xonixx** [raygard/wak#3]
All good:
```
$ awk 'BEGIN { print system("exit 7") }'
7
$ /home/xonix/soft/wak/exe/wak 'BEGIN { print system("exit 7") }'
7

```

Bug:
```
$ awk 'BEGIN { print system("") }'
0
$ /home/xonix/soft/wak/exe/wak 'BEGIN { print system("") }'
256
```

**Comment by iriswebb** [comment]
It's the WEXITSTATUS code that's making this happen, adding 256 if the return value is less than 256

This diff fixes this:
```diff
4396c4396
<         r = r >= 256 ? WEXITSTATUS(r) : r + 256;
---
>         r = !r || r >= 256 ? WEXITSTATUS(r) : r + 256;
```

**Comment by raygard** [comment]
I changed that line to: `if (WIFEXITED(r)) r = WEXITSTATUS(r);`

I haven't studied the matter enough to be sure that's a correct fix, but it fixes this problem.

**Comment by xonixx** [comment]
I can confirm that with the latest fixes in main branch `wak` now passes the testsuite of https://github.com/xonixx/makesure :+1:

**Comment by raygard** [comment]
@xonixx , makesure looks like an interesting awk project. I will look into it when I get a chance. Thanks for the bug report!
